In [1]:
from torch.autograd import Variable
import numpy as np
import torch
import torch.nn.functional as F
import torch.optim as optim

In [23]:

x_data = np.array(((1.0,2.0),(3.0,4.0),(5.0,6.)))
y_data = np.array(((2.0,6.0),(6.0,12.0),(10.0,18.0)))

x_data = torch.tensor(x_data).reshape(3,2).float()
y_data = torch.tensor(y_data).reshape(3,2).float()

w = torch.randn(2).reshape(1,2)

w.requires_grad = True

print(w.size())
print(w)

def forward(x):
    return torch.mul(x , w)

def loss(x,y):
    y_pred = forward(x)
    y_loss = 0
    for y_p, y_r in zip(y_pred.view(-1),y.view(-1)):
        y_loss += (y_p-y_r)**2
    return y_loss

l = loss(x_data,y_data)

print(l)

torch.Size([1, 2])
tensor([[0.4741, 1.0385]], requires_grad=True)
tensor(296.9496, grad_fn=<AddBackward0>)


In [24]:
input_data = torch.tensor((6.0,7.0)).reshape(1,2)
print(input_data)
print("predict (before training)", 4 , forward(input_data))

tensor([[6., 7.]])
('predict (before training)', 4, tensor([[2.8449, 7.2694]], grad_fn=<MulBackward0>))


In [25]:
epoch = range(1,30)
for i in epoch:
    for x, y in zip(x_data,y_data):
#         use the mse loss of torch 
        l = F.mse_loss(forward(x),y)
        l.backward()
        
        
        w.data = w.data - 0.01* w.grad.data
        print("w.data:",w.data,"w.grad:", w.grad)
        w.grad.data.zero_()
        
    print("epoch:",i, ", loss:",l)
    
print("predict (after training)", 4 , forward(input_data).data)

('w.data:', tensor([[0.4894, 1.1170]]), 'w.grad:', tensor([[-1.5259, -7.8460]]))
('w.data:', tensor([[0.6254, 1.4182]]), 'w.grad:', tensor([[-13.5954, -30.1288]]))
('w.data:', tensor([[0.9690, 1.9877]]), 'w.grad:', tensor([[-34.3661, -56.9434]]))
('epoch:', 1, ', loss:', tensor(68.6561, grad_fn=<MseLossBackward>))
('w.data:', tensor([[0.9793, 2.0282]]), 'w.grad:', tensor([[-1.0310, -4.0493]]))
('w.data:', tensor([[1.0712, 2.1837]]), 'w.grad:', tensor([[ -9.1861, -15.5494]]))
('w.data:', tensor([[1.3034, 2.4775]]), 'w.grad:', tensor([[-23.2203, -29.3883]]))
('epoch:', 2, ', loss:', tensor(22.7791, grad_fn=<MseLossBackward>))
('w.data:', tensor([[1.3104, 2.4984]]), 'w.grad:', tensor([[-0.6966, -2.0898]]))
('w.data:', tensor([[1.3724, 2.5787]]), 'w.grad:', tensor([[-6.2068, -8.0250]]))
('w.data:', tensor([[1.5293, 2.7304]]), 'w.grad:', tensor([[-15.6894, -15.1672]]))
('epoch:', 3, ', loss:', tensor(8.1182, grad_fn=<MseLossBackward>))
('w.data:', tensor([[1.5340, 2.7411]]), 'w.grad:', tens

### Train a parameters matrix

In [5]:
from torch.autograd import Variable


x_data = np.array(((1.0,2.0),(3.0,4.0)))
y_data = np.array(((5.0,11.0),(11.0,25.0)))

x_data = torch.tensor(x_data).reshape(2,2).float()
y_data = torch.tensor(y_data).reshape(2,2).float()

w = torch.randn(4).reshape(2,2)

w.requires_grad = True

print(w.size())
print(w)

def forward(x):
    return torch.matmul(x , w)

def loss(x,y):
    y_pred = forward(x)
    y_loss = 0
    for y_p, y_r in zip(y_pred.view(-1),y.view(-1)):
        y_loss += (y_p-y_r)**2
    return y_loss

l = loss(x_data,y_data)

print(l)

torch.Size([2, 2])
tensor([[ 0.0925, -0.2972],
        [-1.2969,  1.2793]], requires_grad=True)
tensor(817.3459, grad_fn=<AddBackward0>)


In [6]:
input_data = torch.tensor((3.0,4.0,)).reshape(1,2)
print(input_data)
print("predict (before training)", 3, 4 , forward(input_data))

tensor([[3., 4.]])
('predict (before training)', 3, 4, tensor([[-4.9101,  4.2254]], grad_fn=<MmBackward>))


In [7]:
for x, y in zip(x_data,y_data):
    print("x:",x,"y:",y)

('x:', tensor([1., 2.]), 'y:', tensor([ 5., 11.]))
('x:', tensor([3., 4.]), 'y:', tensor([11., 25.]))


In [8]:
epoch = range(1,500)
for i in epoch:
    for x, y in zip(x_data,y_data):
        l = loss(x,y)
        l.backward()
        
        
        w.data = w.data - 0.01* w.grad.data
        w.grad.data.zero_()
        
    print("epoch:",i, ", loss:",l)
    
print("predict (after training)", 4 , forward(input_data).data)

('epoch:', 1, ', loss:', tensor(558.7407, grad_fn=<AddBackward0>))
('epoch:', 2, ', loss:', tensor(114.2308, grad_fn=<AddBackward0>))
('epoch:', 3, ', loss:', tensor(23.4868, grad_fn=<AddBackward0>))
('epoch:', 4, ', loss:', tensor(4.9117, grad_fn=<AddBackward0>))
('epoch:', 5, ', loss:', tensor(1.0867, grad_fn=<AddBackward0>))
('epoch:', 6, ', loss:', tensor(0.2888, grad_fn=<AddBackward0>))
('epoch:', 7, ', loss:', tensor(0.1176, grad_fn=<AddBackward0>))
('epoch:', 8, ', loss:', tensor(0.0787, grad_fn=<AddBackward0>))
('epoch:', 9, ', loss:', tensor(0.0688, grad_fn=<AddBackward0>))
('epoch:', 10, ', loss:', tensor(0.0657, grad_fn=<AddBackward0>))
('epoch:', 11, ', loss:', tensor(0.0644, grad_fn=<AddBackward0>))
('epoch:', 12, ', loss:', tensor(0.0637, grad_fn=<AddBackward0>))
('epoch:', 13, ', loss:', tensor(0.0632, grad_fn=<AddBackward0>))
('epoch:', 14, ', loss:', tensor(0.0628, grad_fn=<AddBackward0>))
('epoch:', 15, ', loss:', tensor(0.0624, grad_fn=<AddBackward0>))
('epoch:', 16,

('epoch:', 132, ', loss:', tensor(0.0315, grad_fn=<AddBackward0>))
('epoch:', 133, ', loss:', tensor(0.0313, grad_fn=<AddBackward0>))
('epoch:', 134, ', loss:', tensor(0.0311, grad_fn=<AddBackward0>))
('epoch:', 135, ', loss:', tensor(0.0310, grad_fn=<AddBackward0>))
('epoch:', 136, ', loss:', tensor(0.0308, grad_fn=<AddBackward0>))
('epoch:', 137, ', loss:', tensor(0.0306, grad_fn=<AddBackward0>))
('epoch:', 138, ', loss:', tensor(0.0304, grad_fn=<AddBackward0>))
('epoch:', 139, ', loss:', tensor(0.0302, grad_fn=<AddBackward0>))
('epoch:', 140, ', loss:', tensor(0.0301, grad_fn=<AddBackward0>))
('epoch:', 141, ', loss:', tensor(0.0299, grad_fn=<AddBackward0>))
('epoch:', 142, ', loss:', tensor(0.0297, grad_fn=<AddBackward0>))
('epoch:', 143, ', loss:', tensor(0.0295, grad_fn=<AddBackward0>))
('epoch:', 144, ', loss:', tensor(0.0294, grad_fn=<AddBackward0>))
('epoch:', 145, ', loss:', tensor(0.0292, grad_fn=<AddBackward0>))
('epoch:', 146, ', loss:', tensor(0.0290, grad_fn=<AddBackward

('epoch:', 285, ', loss:', tensor(0.0129, grad_fn=<AddBackward0>))
('epoch:', 286, ', loss:', tensor(0.0128, grad_fn=<AddBackward0>))
('epoch:', 287, ', loss:', tensor(0.0127, grad_fn=<AddBackward0>))
('epoch:', 288, ', loss:', tensor(0.0127, grad_fn=<AddBackward0>))
('epoch:', 289, ', loss:', tensor(0.0126, grad_fn=<AddBackward0>))
('epoch:', 290, ', loss:', tensor(0.0125, grad_fn=<AddBackward0>))
('epoch:', 291, ', loss:', tensor(0.0124, grad_fn=<AddBackward0>))
('epoch:', 292, ', loss:', tensor(0.0124, grad_fn=<AddBackward0>))
('epoch:', 293, ', loss:', tensor(0.0123, grad_fn=<AddBackward0>))
('epoch:', 294, ', loss:', tensor(0.0122, grad_fn=<AddBackward0>))
('epoch:', 295, ', loss:', tensor(0.0122, grad_fn=<AddBackward0>))
('epoch:', 296, ', loss:', tensor(0.0121, grad_fn=<AddBackward0>))
('epoch:', 297, ', loss:', tensor(0.0120, grad_fn=<AddBackward0>))
('epoch:', 298, ', loss:', tensor(0.0119, grad_fn=<AddBackward0>))
('epoch:', 299, ', loss:', tensor(0.0119, grad_fn=<AddBackward

('epoch:', 410, ', loss:', tensor(0.0062, grad_fn=<AddBackward0>))
('epoch:', 411, ', loss:', tensor(0.0062, grad_fn=<AddBackward0>))
('epoch:', 412, ', loss:', tensor(0.0061, grad_fn=<AddBackward0>))
('epoch:', 413, ', loss:', tensor(0.0061, grad_fn=<AddBackward0>))
('epoch:', 414, ', loss:', tensor(0.0061, grad_fn=<AddBackward0>))
('epoch:', 415, ', loss:', tensor(0.0060, grad_fn=<AddBackward0>))
('epoch:', 416, ', loss:', tensor(0.0060, grad_fn=<AddBackward0>))
('epoch:', 417, ', loss:', tensor(0.0060, grad_fn=<AddBackward0>))
('epoch:', 418, ', loss:', tensor(0.0059, grad_fn=<AddBackward0>))
('epoch:', 419, ', loss:', tensor(0.0059, grad_fn=<AddBackward0>))
('epoch:', 420, ', loss:', tensor(0.0059, grad_fn=<AddBackward0>))
('epoch:', 421, ', loss:', tensor(0.0058, grad_fn=<AddBackward0>))
('epoch:', 422, ', loss:', tensor(0.0058, grad_fn=<AddBackward0>))
('epoch:', 423, ', loss:', tensor(0.0058, grad_fn=<AddBackward0>))
('epoch:', 424, ', loss:', tensor(0.0057, grad_fn=<AddBackward

## Gaussian Probability

In [9]:
from scipy.stats import norm

In [10]:
r = np.array((0))
r
norm.pdf(0,0,1)

0.3989422804014327

## Plot some points

In [11]:
# import matplotlib.pyplot as plt
#     plt.scatter(i[4][0],i[4][1])

## Train the Region q function

In [1]:
import Recovery_RL_Agent
import env_robot
import numpy as np
import torch

In [2]:
robot = env_robot.Env(dim=2)
agent = Recovery_RL_Agent.Agent()

goal_array = np.array(([100,100],[100,300],[300,300]))
demo_act_dict = agent.demo_record(goal_array)
demo_act_dict

OrderedDict([('0', array([100, 100])),
             ('1', array([100, 300])),
             ('2', array([300, 300]))])

In [3]:
repeat_times = 100

for i in range(0,repeat_times):
#     executing the demo action and restore experience tuples in agent
    episode_record = robot.execute_demo_act(demo_act_dict)
    print(episode_record[0])
    agent.exp_record(episode_record)
    # Reset env, back to start point
    robot.test_reset()
    

([0, 0], array([0.33776659, 0.31148162, 0.14767294, 0.33123982]), {'0': array([100, 100])}, -170.4095106034372, array([100.46003676, 100.36947704]), array([0.52312751, 0.54410129, 0.48650385, 0.51721649]), False)
([0, 0], array([0.47639469, 0.52322328, 0.51924153, 0.45843857]), {'0': array([100, 100])}, -170.56373248672233, array([101.20820351,  99.79813716]), array([0.78925117, 0.75734032, 0.79405914, 0.74421264]), False)
([0, 0], array([0.81207046, 0.76452391, 0.82877538, 0.77314789]), {'0': array([100, 100])}, -170.2319913223396, array([100.37459754, 100.24568677]), array([0.14860486, 0.24044575, 0.14276796, 0.2851679 ]), False)
([0, 0], array([0.25073732, 0.2693521 , 0.11053912, 0.43512782]), {'0': array([100, 100])}, -171.66851906046992, array([ 99.97860987, 102.32111808]), array([0.5328745 , 0.42091987, 0.55165083, 0.48343289]), False)
([0, 0], array([0.47186457, 0.42169232, 0.50597099, 0.38048437]), {'0': array([100, 100])}, -168.90284260282291, array([ 98.43542054, 100.60664648

In [4]:
e_list = agent.get_exp_list()
for e in e_list:
    print(e.done)

False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
True
False
False
Tr

In [5]:
covar = np.array([[1,0],[0,1]])
phi_inf_list = []
for a_dict,mean in zip(demo_act_dict.items(),goal_array):
    action_dict={}
    action_dict[a_dict[0]] = a_dict[1]
    phi_i = (0,action_dict,False,mean,covar)
    phi_inf_list.append(phi_i)

In [6]:
print(phi_inf_list)

[(0, {'0': array([100, 100])}, False, array([100, 100]), array([[1, 0],
       [0, 1]])), (0, {'1': array([100, 300])}, False, array([100, 300]), array([[1, 0],
       [0, 1]])), (0, {'2': array([300, 300])}, False, array([300, 300]), array([[1, 0],
       [0, 1]]))]


In [7]:
agent.test_init_value_function(phi_inf_list)

In [8]:
agent.test_learn_initial_policy()

(array([100, 100]), array([[1, 0],
       [0, 1]]))


ZeroDivisionError: integer division or modulo by zero

## The Multivariate Gaussian Test

In [ ]:
def gaussian_prob(state, mean,covariance, ):
    prob = scipy.stats.multivariate_normal.pdf(state, mean, covariance)
    return prob

In [14]:
import scipy
x = np.array([97.5426399519241,99.8421622379384])
mean = np.array([100.,100.])
covariance = np.array([[1., 0.], [0.,1.]])

a = scipy.stats.multivariate_normal.pdf(x, mean, covariance)
a

0.011753094426066521

In [ ]:
from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt

x, y = np.mgrid[-1:1:.01, -1:1:.01]
print(np.shape(x))

pos = np.empty(x.shape + (2,))
print(x.shape + (2,))

# print(pos)
pos[:, :, 0] = x; pos[:, :, 1] = y
print(pos)
rv = multivariate_normal([0, 0], [[1, 0], [0, 1]])
plt.contourf(x, y, rv.pdf(pos))

## Udacity Pytorch

### Suppose our action space is 4, state space is 3.

In [48]:
Q_value = torch.randn((3,4))
Q_value

tensor([[ 0.8102,  0.4334, -0.4266, -0.0850],
        [-1.1444,  0.1234, -0.2822, -0.1920],
        [-0.7119, -1.3945, -0.6154,  0.1254]])

### 1. Extract specific action Q values

Note: the index in the gather must be tensor.

Note: Becareful with the shape of action_index. ($3*1$ for $3*4$)

In [52]:
action_index = np.array(((1,),(2,),(3,)))

Q_value.gather(1,torch.from_numpy(action_index))

tensor([[ 0.4334],
        [-0.2822],
        [ 0.1254]])

### 2. Extract the max Q value of each state

In [ ]:
Q_value.max(1)[0]

## Calculate the region forward

In [180]:
regions_inf_list = [[100,5,0],[200,5,1],[300,5,2]]
demo_act = [0,1,2]
q = torch.tensor((1.,3.,5.))
q = q.view(1,3)
q.requires_grad = True

In [181]:
from scipy.stats import norm

def qforward(x):
#     prob = []
#     act_delta_mat = []
# #     Compute the act_delta matrix and prob vector
#     for region_inf in regions_inf_list:
#         prob_phi = norm.pdf(x, region_inf[0], region_inf[1])
#         prob.append(prob_phi)
#         act_vec = []
#         for act in demo_act:
#             if act == region_inf[2]:
#                 have_act = 1.
#             else:
#                 have_act = 0.
#             act_vec.append(have_act)
#         act_delta_mat.append(act_vec)
    
    
#     prob = np.array(prob).reshape(1,3)
#     act_delta_mat = np.array(act_delta_mat).reshape(3,3)
    
#     prob = torch.from_numpy(prob).float()
#     act_delta_mat = torch.from_numpy(act_delta_mat).float()


#     numerator = torch.matmul((q * prob) , act_delta_mat)
#     denominator =  torch.matmul(prob , act_delta_mat)
    
# #     print(prob,numerator, denominator)
#     result = numerator/denominator
# ---------------------------------------------------以上方法不能求导，因为0/0会出现了nan。
    a = np.diag((1,1,1))
    p = np.array((1,1,1)).reshape(1,3)
    a = torch.from_numpy(a).float()
    p = torch.from_numpy(p).float()
    numerator = torch.matmul((q * p) , a)
    denominator = torch.matmul(p , a)
    print(numerator, denominator)
    result = numerator/denominator
    return result

In [182]:
xinput = np.array(200)
xinput = torch.from_numpy(xinput).float()
xinput

tensor(200.)

In [183]:
qforward(xinput)

(tensor([[1., 3., 5.]], grad_fn=<MmBackward>), tensor([[1., 1., 1.]]))


tensor(5., grad_fn=<SelectBackward>)

In [184]:

y_r = torch.tensor([10]).float()


for e in range(300):
    y_p = qforward(xinput)
    y_a = y_p[0][2]
    l = F.mse_loss(y_a,y_r)
    l.backward(retain_graph=True)
    print("q.data:",q.data)
    print("q.grad.data:",q.grad.data)
    q.data = q.data - 0.1 * q.grad.data
    q.grad.data.zero_()
    print("eoch ",e,", loss:",l)

(tensor([[1., 3., 5.]], grad_fn=<MmBackward>), tensor([[1., 1., 1.]]))
('q.data:', tensor([[1., 3., 5.]]))
('q.grad.data:', tensor([[  0.,   0., -10.]]))
('eoch ', 0, ', loss:', tensor(25., grad_fn=<MseLossBackward>))
(tensor([[1., 3., 6.]], grad_fn=<MmBackward>), tensor([[1., 1., 1.]]))
('q.data:', tensor([[1., 3., 6.]]))
('q.grad.data:', tensor([[ 0.,  0., -8.]]))
('eoch ', 1, ', loss:', tensor(16., grad_fn=<MseLossBackward>))
(tensor([[1.0000, 3.0000, 6.8000]], grad_fn=<MmBackward>), tensor([[1., 1., 1.]]))
('q.data:', tensor([[1.0000, 3.0000, 6.8000]]))
('q.grad.data:', tensor([[ 0.0000,  0.0000, -6.4000]]))
('eoch ', 2, ', loss:', tensor(10.2400, grad_fn=<MseLossBackward>))
(tensor([[1.0000, 3.0000, 7.4400]], grad_fn=<MmBackward>), tensor([[1., 1., 1.]]))
('q.data:', tensor([[1.0000, 3.0000, 7.4400]]))
('q.grad.data:', tensor([[ 0.0000,  0.0000, -5.1200]]))
('eoch ', 3, ', loss:', tensor(6.5536, grad_fn=<MseLossBackward>))
(tensor([[1.0000, 3.0000, 7.9520]], grad_fn=<MmBackward>),

(tensor([[ 1.0000,  3.0000, 10.0000]], grad_fn=<MmBackward>), tensor([[1., 1., 1.]]))
('q.data:', tensor([[ 1.0000,  3.0000, 10.0000]]))
('q.grad.data:', tensor([[ 0.0000e+00,  0.0000e+00, -3.8147e-06]]))
('eoch ', 112, ', loss:', tensor(3.6380e-12, grad_fn=<MseLossBackward>))
(tensor([[ 1.0000,  3.0000, 10.0000]], grad_fn=<MmBackward>), tensor([[1., 1., 1.]]))
('q.data:', tensor([[ 1.0000,  3.0000, 10.0000]]))
('q.grad.data:', tensor([[ 0.0000e+00,  0.0000e+00, -3.8147e-06]]))
('eoch ', 113, ', loss:', tensor(3.6380e-12, grad_fn=<MseLossBackward>))
(tensor([[ 1.0000,  3.0000, 10.0000]], grad_fn=<MmBackward>), tensor([[1., 1., 1.]]))
('q.data:', tensor([[ 1.0000,  3.0000, 10.0000]]))
('q.grad.data:', tensor([[ 0.0000e+00,  0.0000e+00, -3.8147e-06]]))
('eoch ', 114, ', loss:', tensor(3.6380e-12, grad_fn=<MseLossBackward>))
(tensor([[ 1.0000,  3.0000, 10.0000]], grad_fn=<MmBackward>), tensor([[1., 1., 1.]]))
('q.data:', tensor([[ 1.0000,  3.0000, 10.0000]]))
('q.grad.data:', tensor([[ 0.

('q.data:', tensor([[ 1.0000,  3.0000, 10.0000]]))
('q.grad.data:', tensor([[ 0.0000e+00,  0.0000e+00, -3.8147e-06]]))
('eoch ', 223, ', loss:', tensor(3.6380e-12, grad_fn=<MseLossBackward>))
(tensor([[ 1.0000,  3.0000, 10.0000]], grad_fn=<MmBackward>), tensor([[1., 1., 1.]]))
('q.data:', tensor([[ 1.0000,  3.0000, 10.0000]]))
('q.grad.data:', tensor([[ 0.0000e+00,  0.0000e+00, -3.8147e-06]]))
('eoch ', 224, ', loss:', tensor(3.6380e-12, grad_fn=<MseLossBackward>))
(tensor([[ 1.0000,  3.0000, 10.0000]], grad_fn=<MmBackward>), tensor([[1., 1., 1.]]))
('q.data:', tensor([[ 1.0000,  3.0000, 10.0000]]))
('q.grad.data:', tensor([[ 0.0000e+00,  0.0000e+00, -3.8147e-06]]))
('eoch ', 225, ', loss:', tensor(3.6380e-12, grad_fn=<MseLossBackward>))
(tensor([[ 1.0000,  3.0000, 10.0000]], grad_fn=<MmBackward>), tensor([[1., 1., 1.]]))
('q.data:', tensor([[ 1.0000,  3.0000, 10.0000]]))
('q.grad.data:', tensor([[ 0.0000e+00,  0.0000e+00, -3.8147e-06]]))
('eoch ', 226, ', loss:', tensor(3.6380e-12, gr

In [185]:
print(q)

tensor([[ 1.0000,  3.0000, 10.0000]], requires_grad=True)
