In [2]:
import Recovery_RL_Agent
import env_robot
import numpy as np
# import torch
import region


robot = env_robot.Env(dim=2)
agent = Recovery_RL_Agent.Agent(dim=2)

demo_goal =  [[10,5],[20,20],[30,40],[40,35],[45,45],[50,55]]
robot.demonstration(demo_goal)
demo_act_dict = agent.demo_record(demo_goal)

repeat_times = 2

for i in range(0,repeat_times):
    # executing the demo action and restore experience tuples in agent
    episode_record,_ = robot.execute_separate_demo_act(demo_act_dict)
    agent.exp_record(episode_record)
    # Reset env, back to start point
    robot.test_reset()


exp_tuple_test = agent.get_exp_list()
for e in exp_tuple_test:
    print(e.state)
experience_list = exp_tuple_test
action_dict = demo_act_dict
print(action_dict)
print(experience_list)



obj = region.Region_Cluster(experience_list, action_dict)
r_s = obj.learn_state_region()
for i, mean in enumerate(r_s):
    print("Region {}: {}".format(i, mean[0]) )

    

Env: the original demonstration skills amount is:6 

Env: The demonstration is:
point 0: [10, 5]
point 1: [20, 20]
point 2: [30, 40]
point 3: [40, 35]
point 4: [45, 45]
point 5: [50, 55]


Env: The final goal position is:[50, 55]
Agent: agent has recorded the demonstration as its original skills: OrderedDict([('0', [10, 5]), ('1', [20, 20]), ('2', [30, 40]), ('3', [40, 35]), ('4', [45, 45]), ('5', [50, 55])]) 

[0. 0. 0. 0. 0. 0.]
[10.65609993  4.55748777  0.31301322  0.36952227  0.18402324  0.24908362]
[20.1424475  20.34333412  0.50472557  0.54008907  0.53729985  0.50147035]
[29.92275979 41.27446061  0.73399126  0.81425297  0.67923386  0.75919689]
[41.03094801 34.65644494  1.00855115  1.11632482  0.94027773  1.02958802]
[43.89545957 45.64294078  1.30292724  1.29486469  1.26512616  1.24074794]
[0. 0. 0. 0. 0. 0.]
[8.87774474 3.23007039 0.10977084 0.21472224 0.25124499 0.14200267]
[20.94716506 20.36410461  0.46227295  0.43542408  0.50230124  0.52002256]
[28.40923861 38.85771673  0.68812

AttributeError: 'Experience' object has no attribute 'next_contact'

In [5]:
import torch
torch.ones(1,3)

tensor([[1., 1., 1.]])

In [3]:
np.zeros(3)

array([0., 0., 0.])