In [1]:
from torch.autograd import Variable
import numpy as np
import torch

In [2]:

x_data = np.array((1.0,2.0,3.0,4.0,5.0))
y_data = np.array(((2.0,3.0),(4.0,6.0),(6.0,9.0),(8.0,12.0),(10.0,15.0)))

x_data = torch.tensor(x_data).reshape(5,1).float()
y_data = torch.tensor(y_data).reshape(5,2).float()

w = torch.randn(2).reshape(1,2)

w.requires_grad = True

print(w.size())
print(w)

def forward(x):
    return torch.matmul(x , w)

def loss(x,y):
    y_pred = forward(x)
    y_loss = 0
    for y_p, y_r in zip(y_pred.view(-1),y.view(-1)):
        y_loss += (y_p-y_r)**2
    return y_loss

l = loss(x_data,y_data)

print(l)

torch.Size([1, 2])
tensor([[ 0.9478, -0.5457]], requires_grad=True)
tensor(752.3660, grad_fn=<AddBackward0>)


In [3]:
input_data = torch.tensor((5.0,6.0,7.0)).reshape(3,1)
print(input_data)
print("predict (before training)", 4 , forward(input_data))

tensor([[5.],
        [6.],
        [7.]])
('predict (before training)', 4, tensor([[ 4.7391, -2.7287],
        [ 5.6869, -3.2745],
        [ 6.6347, -3.8202]], grad_fn=<MmBackward>))


In [4]:
epoch = range(1,30)
for i in epoch:
    for x, y in zip(x_data,y_data):
        l = loss(x,y)
        l.backward()
        
        
        w.data = w.data - 0.01* w.grad.data
        print("w.data:",w.data,"w.grad:", w.grad)
        w.grad.data.zero_()
        
    print("epoch:",i, ", loss:",l)
    
print("predict (after training)", 4 , forward(input_data).data)

('w.data:', tensor([[ 0.9689, -0.4748]]), 'w.grad:', tensor([[-2.1044, -7.0915]]))
('w.data:', tensor([[ 1.0514, -0.1968]]), 'w.grad:', tensor([[ -8.2491, -27.7986]]))
('w.data:', tensor([[1.2221, 0.3786]]), 'w.grad:', tensor([[-17.0756, -57.5432]]))
('w.data:', tensor([[1.4710, 1.2174]]), 'w.grad:', tensor([[-24.8925, -83.8852]]))
('w.data:', tensor([[1.7355, 2.1087]]), 'w.grad:', tensor([[-26.4482, -89.1280]]))
('epoch:', 1, ', loss:', tensor(86.4331, grad_fn=<AddBackward0>))
('w.data:', tensor([[1.7408, 2.1265]]), 'w.grad:', tensor([[-0.5290, -1.7826]]))
('w.data:', tensor([[1.7615, 2.1964]]), 'w.grad:', tensor([[-2.0735, -6.9876]]))
('w.data:', tensor([[1.8045, 2.3411]]), 'w.grad:', tensor([[ -4.2922, -14.4644]]))
('w.data:', tensor([[1.8670, 2.5519]]), 'w.grad:', tensor([[ -6.2571, -21.0859]]))
('w.data:', tensor([[1.9335, 2.7760]]), 'w.grad:', tensor([[ -6.6482, -22.4038]]))
('epoch:', 2, ', loss:', tensor(5.4613, grad_fn=<AddBackward0>))
('w.data:', tensor([[1.9348, 2.7804]]), '

### Train a parameters matrix

In [5]:
from torch.autograd import Variable


x_data = np.array(((1.0,2.0),(3.0,4.0)))
y_data = np.array(((5.0,11.0),(11.0,25.0)))

x_data = torch.tensor(x_data).reshape(2,2).float()
y_data = torch.tensor(y_data).reshape(2,2).float()

w = torch.randn(4).reshape(2,2)

w.requires_grad = True

print(w.size())
print(w)

def forward(x):
    return torch.matmul(x , w)

def loss(x,y):
    y_pred = forward(x)
    y_loss = 0
    for y_p, y_r in zip(y_pred.view(-1),y.view(-1)):
        y_loss += (y_p-y_r)**2
    return y_loss

l = loss(x_data,y_data)

print(l)

torch.Size([2, 2])
tensor([[-0.1260,  0.6625],
        [ 0.2531, -1.1166]], requires_grad=True)
tensor(1041.8936, grad_fn=<AddBackward0>)


In [6]:
input_data = torch.tensor((3.0,4.0,)).reshape(1,2)
print(input_data)
print("predict (before training)", 3, 4 , forward(input_data))

tensor([[3., 4.]])
('predict (before training)', 3, 4, tensor([[ 0.6342, -2.4787]], grad_fn=<MmBackward>))


In [7]:
for x, y in zip(x_data,y_data):
    print("x:",x,"y:",y)

('x:', tensor([1., 2.]), 'y:', tensor([ 5., 11.]))
('x:', tensor([3., 4.]), 'y:', tensor([11., 25.]))


In [8]:
epoch = range(1,500)
for i in epoch:
    for x, y in zip(x_data,y_data):
        l = loss(x,y)
        l.backward()
        
        
        w.data = w.data - 0.01* w.grad.data
        w.grad.data.zero_()
        
    print("epoch:",i, ", loss:",l)
    
print("predict (after training)", 4 , forward(input_data).data)

('epoch:', 1, ', loss:', tensor(698.1529, grad_fn=<AddBackward0>))
('epoch:', 2, ', loss:', tensor(140.1510, grad_fn=<AddBackward0>))
('epoch:', 3, ', loss:', tensor(27.6346, grad_fn=<AddBackward0>))
('epoch:', 4, ', loss:', tensor(5.2299, grad_fn=<AddBackward0>))
('epoch:', 5, ', loss:', tensor(0.8973, grad_fn=<AddBackward0>))
('epoch:', 6, ', loss:', tensor(0.1187, grad_fn=<AddBackward0>))
('epoch:', 7, ', loss:', tensor(0.0068, grad_fn=<AddBackward0>))
('epoch:', 8, ', loss:', tensor(0.0049, grad_fn=<AddBackward0>))
('epoch:', 9, ', loss:', tensor(0.0139, grad_fn=<AddBackward0>))
('epoch:', 10, ', loss:', tensor(0.0199, grad_fn=<AddBackward0>))
('epoch:', 11, ', loss:', tensor(0.0229, grad_fn=<AddBackward0>))
('epoch:', 12, ', loss:', tensor(0.0242, grad_fn=<AddBackward0>))
('epoch:', 13, ', loss:', tensor(0.0248, grad_fn=<AddBackward0>))
('epoch:', 14, ', loss:', tensor(0.0249, grad_fn=<AddBackward0>))
('epoch:', 15, ', loss:', tensor(0.0249, grad_fn=<AddBackward0>))
('epoch:', 16,

('epoch:', 138, ', loss:', tensor(0.0122, grad_fn=<AddBackward0>))
('epoch:', 139, ', loss:', tensor(0.0121, grad_fn=<AddBackward0>))
('epoch:', 140, ', loss:', tensor(0.0121, grad_fn=<AddBackward0>))
('epoch:', 141, ', loss:', tensor(0.0120, grad_fn=<AddBackward0>))
('epoch:', 142, ', loss:', tensor(0.0119, grad_fn=<AddBackward0>))
('epoch:', 143, ', loss:', tensor(0.0119, grad_fn=<AddBackward0>))
('epoch:', 144, ', loss:', tensor(0.0118, grad_fn=<AddBackward0>))
('epoch:', 145, ', loss:', tensor(0.0117, grad_fn=<AddBackward0>))
('epoch:', 146, ', loss:', tensor(0.0117, grad_fn=<AddBackward0>))
('epoch:', 147, ', loss:', tensor(0.0116, grad_fn=<AddBackward0>))
('epoch:', 148, ', loss:', tensor(0.0115, grad_fn=<AddBackward0>))
('epoch:', 149, ', loss:', tensor(0.0115, grad_fn=<AddBackward0>))
('epoch:', 150, ', loss:', tensor(0.0114, grad_fn=<AddBackward0>))
('epoch:', 151, ', loss:', tensor(0.0113, grad_fn=<AddBackward0>))
('epoch:', 152, ', loss:', tensor(0.0113, grad_fn=<AddBackward

('epoch:', 307, ', loss:', tensor(0.0046, grad_fn=<AddBackward0>))
('epoch:', 308, ', loss:', tensor(0.0045, grad_fn=<AddBackward0>))
('epoch:', 309, ', loss:', tensor(0.0045, grad_fn=<AddBackward0>))
('epoch:', 310, ', loss:', tensor(0.0045, grad_fn=<AddBackward0>))
('epoch:', 311, ', loss:', tensor(0.0044, grad_fn=<AddBackward0>))
('epoch:', 312, ', loss:', tensor(0.0044, grad_fn=<AddBackward0>))
('epoch:', 313, ', loss:', tensor(0.0044, grad_fn=<AddBackward0>))
('epoch:', 314, ', loss:', tensor(0.0044, grad_fn=<AddBackward0>))
('epoch:', 315, ', loss:', tensor(0.0043, grad_fn=<AddBackward0>))
('epoch:', 316, ', loss:', tensor(0.0043, grad_fn=<AddBackward0>))
('epoch:', 317, ', loss:', tensor(0.0043, grad_fn=<AddBackward0>))
('epoch:', 318, ', loss:', tensor(0.0043, grad_fn=<AddBackward0>))
('epoch:', 319, ', loss:', tensor(0.0042, grad_fn=<AddBackward0>))
('epoch:', 320, ', loss:', tensor(0.0042, grad_fn=<AddBackward0>))
('epoch:', 321, ', loss:', tensor(0.0042, grad_fn=<AddBackward

('epoch:', 434, ', loss:', tensor(0.0022, grad_fn=<AddBackward0>))
('epoch:', 435, ', loss:', tensor(0.0022, grad_fn=<AddBackward0>))
('epoch:', 436, ', loss:', tensor(0.0021, grad_fn=<AddBackward0>))
('epoch:', 437, ', loss:', tensor(0.0021, grad_fn=<AddBackward0>))
('epoch:', 438, ', loss:', tensor(0.0021, grad_fn=<AddBackward0>))
('epoch:', 439, ', loss:', tensor(0.0021, grad_fn=<AddBackward0>))
('epoch:', 440, ', loss:', tensor(0.0021, grad_fn=<AddBackward0>))
('epoch:', 441, ', loss:', tensor(0.0021, grad_fn=<AddBackward0>))
('epoch:', 442, ', loss:', tensor(0.0021, grad_fn=<AddBackward0>))
('epoch:', 443, ', loss:', tensor(0.0021, grad_fn=<AddBackward0>))
('epoch:', 444, ', loss:', tensor(0.0020, grad_fn=<AddBackward0>))
('epoch:', 445, ', loss:', tensor(0.0020, grad_fn=<AddBackward0>))
('epoch:', 446, ', loss:', tensor(0.0020, grad_fn=<AddBackward0>))
('epoch:', 447, ', loss:', tensor(0.0020, grad_fn=<AddBackward0>))
('epoch:', 448, ', loss:', tensor(0.0020, grad_fn=<AddBackward

## Gaussian Probability

In [9]:
from scipy.stats import norm

In [10]:
r = np.array((0))
r
norm.pdf(0,0,1)

0.3989422804014327

## Plot some points

In [11]:
# import matplotlib.pyplot as plt
#     plt.scatter(i[4][0],i[4][1])

## Train the Region q function

In [12]:
import Recovery_RL_Agent
import env_robot
import numpy as np
import torch

In [13]:
robot = env_robot.Env(dim=2)
agent = Recovery_RL_Agent.Agent()

goal_array = np.array(([100,100],[100,300],[300,300]))
demo_act_dict = agent.demo_record(goal_array)
demo_act_dict

OrderedDict([('0', array([100, 100])),
             ('1', array([100, 300])),
             ('2', array([300, 300]))])

In [14]:
repeat_times = 100

for i in range(0,repeat_times):
    # executing the demo action and restore experience tuples in agent
    episode_record = robot.execute_demo_act(demo_act_dict)
    agent.exp_record(episode_record)
    # Reset env, back to start point
    robot.test_reset()

In [19]:
e_list = agent.get_exp_list()
for e in e_list:
    print(e[3])

-167.729925822
-241.527211133
-201.268033794
-171.103361549
-238.130539908
-200.755127852
-169.763103594
-238.068553856
-202.228565878
-167.696367303
-242.893167664
-199.994310988
-170.549457027
-237.335741976
-202.160308361
-167.592003157
-243.076433498
-198.952115118
-169.013142963
-243.051041097
-201.5909189
-171.383004227
-238.397445976
-198.945203889
-167.849535099
-240.487110339
-199.954442942
-169.113994843
-242.505497692
-199.06277156
-169.480652555
-241.471252479
-200.949475111
-168.229487859
-239.959866395
-200.142654901
-170.297617533
-239.676717875
-200.373959205
-170.375764792
-240.663100844
-199.074295073
-171.783401655
-242.087949241
-200.645345347
-169.130732169
-241.585435885
-198.176609213
-169.243118447
-239.198554129
-200.446748276
-170.911772595
-237.845747125
-201.418292244
-170.030344897
-237.824562312
-201.80294188
-167.568740465
-241.405220869
-198.63493197
-169.506831779
-240.572578918
-202.213181734
-171.804468178
-239.038889412
-201.126298537
-170.627264566


In [16]:
def gaussian_prob(state, mean,covariance, ):
    prob = scipy.stats.multivariate_normal.pdf(state, mean, covariance)
    return prob

In [17]:
import scipy
x = np.array([0.,0.])
mean = np.array([0.,0.])
covariance = np.array([[1., 0.], [0.,1.]])

a = scipy.stats.multivariate_normal.pdf(x, mean, covariance)
a

0.15915494309189535

In [18]:
from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt

x, y = np.mgrid[-1:1:.01, -1:1:.01]
print(np.shape(x))

pos = np.empty(x.shape + (2,))
print(x.shape + (2,))

# print(pos)
pos[:, :, 0] = x; pos[:, :, 1] = y
print(pos)
rv = multivariate_normal([0, 0], [[1, 0], [0, 1]])
plt.contourf(x, y, rv.pdf(pos))

(200, 200)
(200, 200, 2)
[[[-1.   -1.  ]
  [-1.   -0.99]
  [-1.   -0.98]
  ...
  [-1.    0.97]
  [-1.    0.98]
  [-1.    0.99]]

 [[-0.99 -1.  ]
  [-0.99 -0.99]
  [-0.99 -0.98]
  ...
  [-0.99  0.97]
  [-0.99  0.98]
  [-0.99  0.99]]

 [[-0.98 -1.  ]
  [-0.98 -0.99]
  [-0.98 -0.98]
  ...
  [-0.98  0.97]
  [-0.98  0.98]
  [-0.98  0.99]]

 ...

 [[ 0.97 -1.  ]
  [ 0.97 -0.99]
  [ 0.97 -0.98]
  ...
  [ 0.97  0.97]
  [ 0.97  0.98]
  [ 0.97  0.99]]

 [[ 0.98 -1.  ]
  [ 0.98 -0.99]
  [ 0.98 -0.98]
  ...
  [ 0.98  0.97]
  [ 0.98  0.98]
  [ 0.98  0.99]]

 [[ 0.99 -1.  ]
  [ 0.99 -0.99]
  [ 0.99 -0.98]
  ...
  [ 0.99  0.97]
  [ 0.99  0.98]
  [ 0.99  0.99]]]
