In [4]:
import Recovery_RL_Agent
import env_robot
import numpy as np
# import torch
import region


robot = env_robot.Env(dim=2)
agent = Recovery_RL_Agent.Agent(dim=2)

demo_goal =  [[10,5],[20,20],[30,40],[40,35],[45,45],[50,55]]
robot.demonstration(demo_goal)
demo_act_dict = agent.demo_record(demo_goal)

repeat_times = 100

for i in range(0,repeat_times):
    # executing the demo action and restore experience tuples in agent
    episode_record,seperate_s_c_record = robot.execute_seperate_demo_act(demo_act_dict)
    agent.seperate_exp_record(seperate_s_c_record)
    agent.exp_record(episode_record)
    # Reset env, back to start point
    robot.test_reset()


exp_tuple_test = agent.get_seperate_exp_list()
for e in exp_tuple_test:
    print(e.contact)
experience_list = exp_tuple_test
action_dict = demo_act_dict




obj = region.Region_Cluster(experience_list, action_dict)
r_s = obj.learn_state_region()
for i, mean in enumerate(r_s):
    print("Region {}: {}".format(i, mean[0]) )

    

Env: the original demonstration skills amount is:6 

Env: The demonstration is:
point 0: [10, 5]
point 1: [20, 20]
point 2: [30, 40]
point 3: [40, 35]
point 4: [45, 45]
point 5: [50, 55]


Env: The final goal position is:[50, 55]
Agent: agent has recorded the demonstration as its original skills: OrderedDict([('0', [10, 5]), ('1', [20, 20]), ('2', [30, 40]), ('3', [40, 35]), ('4', [45, 45]), ('5', [50, 55])]) 

[0. 0. 0. 0.]
[0.17661246 0.21654207 0.22121476 0.38220788]
[0.55202546 0.5595237  0.55583492 0.67904041]
[0.69990146 0.78605941 0.69074798 0.80297667]
[1.06774539 0.99126244 1.04099916 1.02048909]
[1.12672615 1.17213995 1.20360885 1.23107245]
[0. 0. 0. 0.]
[0.35762338 0.09726739 0.21614667 0.2285118 ]
[0.47129315 0.41100456 0.47071045 0.52318308]
[0.71548773 0.69940923 0.70023016 0.91109728]
[1.02991225 0.9357207  0.95046087 0.99190574]
[1.34365549 1.19760295 1.31429898 1.23199218]
[0. 0. 0. 0.]
[0.13961788 0.26238707 0.26030017 0.33606637]
[0.52942285 0.50533849 0.48319123 0.4

Region 0: [9.96446076 4.79716628 0.25031778 0.24297504 0.24355369 0.25280842]
Region 1: [20.087284   19.98988408  0.48946071  0.48554127  0.49456222  0.49872497]
Region 2: [30.0045263  39.88449761  0.75656954  0.74209306  0.75687384  0.75465885]
Region 3: [39.87963994 35.06816544  0.99822109  0.99100429  1.00611515  1.0003128 ]
Region 4: [44.89697381 44.85904484  1.25530756  1.24128228  1.24565207  1.25100701]


In [5]:
import torch
torch.ones(1,3)

tensor([[1., 1., 1.]])

In [3]:
np.zeros(3)

array([0., 0., 0.])